[build]
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/moex-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200